[general]
import = ["~/.config/alacritty/themes/catppuccin-latte.toml"]

[window]
opacity = 0.95
blur = true
decorations = "Full"
padding = { x = 6, y = 6 }
dynamic_padding = true
title = "Alacritty"

[font]
size = 12.5

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 650
